service: serverless-backend
frameworkVersion: '3'

plugins:
 - serverless-offline
 - serverless-express

provider:
  name: aws
  runtime: nodejs16.x

functions:
  api:
    handler: handler.handler
    events:
      - httpApi: '*'
        
      
      
